# Powered by EchtOps.com 
# (Pocket Friendly and Reliable Infrastructure Services for Web3, AI and Deeptech)

title: CryptoTrendz
author:
  name: CryptoTrendz
  email: connect@echtops.com

# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Stay ahead in the market with curated and minimal insights. 

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Addons
header_pages:
  - about.md
  - terms.md
  - privacy.md

# Skin
minima:
  # classic	           Default, light color scheme.
  skin: classic

  # Excerpts are short summary
  show_excerpts: true

  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  social_links:
   - title: LinkedIn
     icon: linkedin
     url: "https://www.linkedin.com/company/cryptotrendz/posts/"
   - title: Telegram
     icon: telegram
     url: "https://t.me/CryptoTrndz"
   - title: Quora
     icon: quora
     url: "https://CryptoTrendz.quora.com"
   - title: RSS Feeds
     icon: readme
     url: "https://cryptoTrendz.echtops.com/feed.xml"
   - title: Launching Soon on Instagram
     icon: instagram
     url: "https://www.instagram.com/cryptotrndz/"
   - title: Launching Soon on X (formerly Twitter)
     icon: instagram
     icon: x-twitter
     url: "https://x.com/CryptoTrndz"

# Let's Paginate
paginate: 7
paginate_path: "/page:num/"

## Showtime :)