# Powered by OpsByte - Value to Money, Reliable Infra & Cloud Services for Web3, AI, Digital Platforms and Digital products )

title: CryptoTrendz
author:
  name: OpsByte - Reliable and Affordable Web3 Ops
  email: info@opsbyte.com

# If you want to omit the line-break after the end of text, use `>-` instead.
tagline: OpsByte - The Reliable and Affordable Web3 Ops

description: >
  Stay informed about the cryptocurrency market with authoritative, data-driven insights tailored for professionals and investors. Navigate the blockchain landscape with confidence.

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Addons
header_pages:
  - about.md
  - terms.md
  - privacy.md

# Skin
minima:
  # classic	           Default, light color scheme.
  skin: classic

  # Excerpts are short summary
  show_excerpts: true

  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  social_links:
   - title: LinkedIn
     icon: linkedin
     url: "https://www.linkedin.com/company/cryptotrendz/posts/"
   - title: Telegram
     icon: telegram
     url: "https://t.me/CryptoTrndz"
   - title: Quora
     icon: quora
     url: "https://CryptoTrendz.quora.com"
   - title: X (formerly Twitter)
     icon: x-twitter
     url: "https://x.com/_CryptoTrendz_"
   - title: Instagram
     icon: instagram
     url: "https://www.instagram.com/cryptotrndz/"
   - title: RSS Feeds
     icon: readme
     url: "https://ctrendz.opsbyte.com/feed.xml"

# Let's Paginate
paginate: 8
paginate_path: "/page:num/"

## Showtime :)
